# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-30 00:15
from __future__ import unicode_literals

from django.db import migrations


# noinspection PyUnusedLocal
def backwards_func(apps, schema_editor):
    apps.get_model('orders', 'PaymentMethod').objects.all().delete()


# noinspection PyUnusedLocal
def forwards_func(apps, schema_editor):
    payment_method_model = apps.get_model('orders', 'PaymentMethod')

    payment_method_model.objects.create(label='Apple Card')
    payment_method_model.objects.create(label='Mastercard 1709')
    payment_method_model.objects.create(label='Mastercard 1986')
    payment_method_model.objects.create(label='Visa')


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func)
    ]
