# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-11-04 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_add_payment_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='picked_up',
            field=models.NullBooleanField(default=None),
        ),
    ]
