# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-15 13:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.FloatField(help_text='Tax rate at time of sale (in percentage)')),
                ('discount', models.FloatField(default=0, help_text='Price discount at time of sale (in percentage)')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price the item sold for (includes sales tax)', max_digits=10)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, help_text='Commission made on this item', max_digits=10, null=True)),
                ('date', models.DateField(blank=True, db_index=True, help_text='Date on which the item sold', null=True)),
                ('item', models.ForeignKey(help_text='Item which was sold', on_delete=django.db.models.deletion.CASCADE, to='inventory.Item')),
                ('user', models.ForeignKey(help_text='User account this information belongs to', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('item__number', 'date', 'item__desc'),
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=50)),
                ('state', localflavor.us.models.USStateField(max_length=2)),
                ('sales_tax', models.FloatField(help_text='Current tax rate (in percentage)')),
            ],
            options={
                'verbose_name_plural': 'Taxes',
                'ordering': ('state', 'county'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='tax',
            unique_together=set([('county', 'state')]),
        ),
        migrations.AlterUniqueTogether(
            name='sale',
            unique_together=set([('item', 'user')]),
        ),
    ]
