# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-18 19:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20220416_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='qty',
            field=models.PositiveIntegerField(default=1, help_text='How many were sold', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
