#!/bin/sh

# Run through all unit tests

TESTS="common inventory sales"

dir="`dirname $0`"
if [ -n "$1" ]
then
    browser="$1"
else
    browser="firefox"
fi

cd $dir

for test in $TESTS
do
    if [ "$test" = "inventory" -o "$test" = "sales" ]
    then
        browser_arg="--behave_browser $browser"
    else
        browser_arg=""
    fi

    ./manage.py test $browser_arg $test
done

exit 0

