# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-15 13:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the category', max_length=50)),
                ('desc', models.CharField(blank=True, help_text='Category description', max_length=100, null=True)),
                ('remove', models.BooleanField(default=False, help_text='Check to remove this item from the category list')),
                ('user', models.ForeignKey(help_text='User account this category belongs to', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Item number')),
                ('desc', models.CharField(help_text='Description of the item', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the item', max_digits=10)),
                ('worth', models.DecimalField(blank=True, decimal_places=2, help_text='How much is the item actually worth', max_digits=10, null=True)),
                ('picture', models.ImageField(blank=True, help_text='Item image', null=True, upload_to='inventory.ItemImage/data/filename/mimetype')),
                ('commission', models.CharField(blank=True, help_text='Commission on this item (use % to indicate percentage)', max_length=5)),
                ('comments', models.TextField(blank=True)),
                ('remove', models.BooleanField(default=False, help_text='Check to remove this item from inventory (and not because it was sold)')),
                ('category', models.ForeignKey(blank=True, help_text='Category this item is in', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Category')),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('remove', models.BooleanField(default=False, help_text='Check to remove this seller')),
                ('user', models.ForeignKey(help_text='User account this item belongs to', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.AddField(
            model_name='item',
            name='sellers',
            field=models.ManyToManyField(help_text='Seller(s) of this item', to='inventory.Seller'),
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(help_text='User account this item belongs to', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='seller',
            unique_together=set([('first_name', 'last_name', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set([('user', 'number', 'category')]),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('user', 'name')]),
        ),
    ]
