# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-16 19:20
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('sku',)},
        ),
        migrations.AddField(
            model_name='item',
            name='qty',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='sku',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='supplier',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='wholesale',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Wholesale price of the item', max_digits=10),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='item',
            name='number',
        ),
        migrations.RemoveField(
            model_name='item',
            name='worth',
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set([('sku', 'user', 'category')]),
        ),
    ]
