# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-04-06 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20230404_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Delete this item from inventory'),
        ),
    ]
