# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-29 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventory_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Vendor this item was purchased from', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Vendor'),
        ),
    ]
