# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-30 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20230629_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='notes',
            field=models.TextField(blank=True, help_text='Any miscellaneous information can go here'),
        ),
    ]
