# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-10-05 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20230925_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='qty_bought',
            field=models.PositiveIntegerField(default=0, help_text='Quantity of this item purchased'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Wholesale price per item unit', max_digits=10),
        ),
    ]
