# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-29 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Vendor's name", max_length=50)),
                ('website', models.URLField(help_text="Vendor's website")),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
