# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-29 23:42
from __future__ import unicode_literals

from django.db import migrations


# noinspection PyUnusedLocal
def backwards_func(apps, schema_editor):
    old_vendor_model = apps.get_model('inventory', 'Vendor')
    new_vendor_model = apps.get_model('vendors', 'Vendor')

    for new_vendor in new_vendor_model.objects.all():
        old_vendor_model.objects.get_or_create(id=new_vendor.id, name=new_vendor.name)


# noinspection PyUnusedLocal
def forwards_func(apps, schema_editor):
    old_vendor_model = apps.get_model('inventory', 'Vendor')
    new_vendor_model = apps.get_model('vendors', 'Vendor')

    for old_vendor in old_vendor_model.objects.all():
        new_vendor_model.objects.create(id=old_vendor.id, name=old_vendor.name)


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func)
    ]
