# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-30 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendor_running_investment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='website',
            field=models.URLField(blank=True, help_text="Vendor's website", null=True),
        ),
    ]
