# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-30 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_auto_20230629_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(help_text="Vendor's name", max_length=50, unique=True),
        ),
    ]
