# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-11-04 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_auto_20230630_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='running_investment',
        ),
    ]
